[package]
name = "rust-servers-services-apps"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.2.1"
actix-rt = "2.7.0"

# Data 직렬화 라이브러리
serde = {version = "1.0.110", features = ["derive"]}

# 다른 유틸리티
chrono = {version = "0.4.11", features = ["serde"]}

[[bin]]
name = "basic-server"

[[bin]]
name = "tutor-service"
